### ISSUE TITLE
add notification area

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#474]
Use the bottom left of the screen to display (temp) notifications. Multiple notifications can be shown at the same time. The notifications can be shown for a few seconds, or until it's discarded. Calling the `showNotification` method should return a notification object with a `discard` method.

In the future, notifications can be expanded to include links (for example, undo) with a callback method supplied at creation. Text should be left-aligned, the action link right-aligned, in caps and using an accent color.

Maybe also add some kind of loading indicator?

Some css:

``` css
.notifications {
  bottom: 24px;
  left: 24px;
  position: fixed;
}
.notification {
  background-color: #404040; // or #323232
  border-radius: 3px;
  box-shadow: 0 0 2px rgba(0, 0, 0, 0.12),0 2px 4px rgba(0, 0, 0, 0.24);
  color: #FFF;
  display: inline-block;
  line-height: 20px;
  margin-top: 8px;
  padding: 16px; // or 20px left, 10px on other sides
}
```

_[Original issue](https://github.ugent.be/unipept/unipept/issues/474) by @bmesuere on Sat Mar 21 2015 at 20:35._
_Closed by @bmesuere on Sun Mar 22 2015 at 15:08._
