### ISSUE TITLE
Add ellipsis to too long peptides

### ISSUE THREAD

**Issue by beardhatcode** [unipept/unipept#621]
I haven't taken a look at te CSS yet. So I'll just dump this here for someone else or future me
![current state](https://github.ugent.be/storage/user/426/files/06a9eaaa-c570-11e7-9c91-efda41f66b18)

The following CSS fixes the issue
```CSS
ul li a{
    text-overflow: ellipsis;
    overflow: hidden;
    display: block;
}
```
![with eliipsis](https://github.ugent.be/storage/user/426/files/088bf606-c570-11e7-896e-060beceee443)

Occurs with PRIDE assay 8500

_[Original issue](https://github.ugent.be/unipept/unipept/issues/621) by @beardhatcode on Thu Nov 09 2017 at 17:07._
_Closed by @bmesuere on Mon Aug 13 2018 at 15:27._
